### ISSUE TITLE
(Suggestion) Tester->Send and re-sending

### ISSUE THREAD

**Issue by paveljamal** [jjaquinta/EchoSim#1]
When you are in development, you are constantly resending the same few requests. Most often the last one. Currently clicking Tester->Send clears the "Say:" input box but not the box under it.

Suggestions:
1) Keep track of commands sent, let users use Up/Down to select them
2) Add Send & Clear button, so Send won't clear any more
3) Add a history combobox

**Comment by jjaquinta** [comment]
Working on this now. I hope to have a release out tonight.
I'm not implementing it exactly as you are suggesting, but I think it will capture and present the desired functionality.

**Comment by jjaquinta** [comment]
Updated in today's release. See the release notes. It isn't exactly the UI you suggested, but I think it addresses the raised issues.
1) The comments sent are already displayed in the transcript window. You can now double click on one of those to populate your input box with the input text from that command.
2) Send no longer clears the input text. But it does select everything. This maintains the previous behavior where you could type "line one<enter>line two<enter>" and have it send one line after the other. But it also supports the desired behavior "line one<enter><enter>" where you can resend a line without extra work.
3) This should be covered by 1.

**Comment by paveljamal** [comment]
Works great.
