### ISSUE TITLE
No Signature or SignatureCertUrl headers

### ISSUE THREAD

**Issue by oznetmaster** [jjaquinta/EchoSim#3]
The http request generated by the simulator is missing both a Signature and a SignatureCertChainUrl header.

As a result, the simulator is unable to communicate with any valid skill (one which works correctly with amazon).

Can these two headers be added. Since the SignatureCertChainUrl appears to be a constant value, it could be entered on the App tab and saved with the preset.

The Signature should be easily generated, since it is validated in the skill.

Without these two headers, the simulator is useless with current skills :(

**Comment by jjaquinta** [comment]
I think it's documented somewhere that you should turn on signature validation. For Java it is just a system property setting you make.

For some reason I remember it was hard to generate these values.
